### ISSUE TITLE
Integration does not load after update to 2.4.1

### ISSUE THREAD

**Issue by windmueller** [MaxGrmm/EF-PowerOcean-TcpModbus#64]
### Home Assistant Version

2026.6.3

### Device Type

PowerOcean Three Phase

### Integration Version

2.4.1

### Device Firmware Version

V5.1.37.10

### Bug Description

After upgrading the integration in Home Assistant, it fails to load:

```
Setup failed for custom integration 'ef_powerocean_tcpmodbus': Unable to import component: cannot import name 'UnitOfRatio' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

Downgrading to 2.4.0 fixes the issue.

### Steps to Reproduce

1. Configure version 2.4.0
2. Upgrade to 2.4.1
3. Restart Home Assistant as requested

### Relevant Log Entries

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1022, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1082, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/ef_powerocean_tcpmodbus/__init__.py", line 14, in <module>
    from .const import DOMAIN
  File "/config/custom_components/ef_powerocean_tcpmodbus/const.py", line 10, in <module>
    from homeassistant.const import (
    ...<7 lines>...
    )
ImportError: cannot import name 'UnitOfRatio' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1042, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1082, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/ef_powerocean_tcpmodbus/__init__.py", line 14, in <module>
    from .const import DOMAIN
  File "/config/custom_components/ef_powerocean_tcpmodbus/const.py", line 10, in <module>
    from homeassistant.const import (
    ...<7 lines>...
    )
ImportError: cannot import name 'UnitOfRatio' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

### Diagnostics

```json

```

**Comment by Grimmwolf-GB** [comment]
Dev2 still worked, dev3 and the release fail to start.

**Comment by windmark** [comment]
Oh this is my fault, the `UnitOfRatio` seems to only have been introduced in home assistant version 2026.7. I'll fix immediately

**Comment by windmark** [comment]
I have a fix for this in https://github.com/MaxGrmm/EF-PowerOcean-TcpModbus/pull/67

**Comment by fuchsi585** [comment]
I create Release [2.4.2](https://github.com/MaxGrmm/EF-PowerOcean-TcpModbus/releases/tag/v2.4.2).

**Comment by windmark** [comment]
@windmueller @Grimmwolf-GB Can you confirm that 2.4.2 works?

**Comment by windmueller** [comment]
Unfortunately, 2.4.2 is also broken.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 796, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ef_powerocean_tcpmodbus/__init__.py", line 79, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2741, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1193, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1193, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1193, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1105, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1280, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1312, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/ef_powerocean_tcpmodbus/sensor.py", line 11, in <module>
    from homeassistant.const import (
    ...<8 lines>...
    )
ImportError: cannot import name 'UnitOfRatio' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

Please reopen the issue since I do not have the permission.

**Comment by windmark** [comment]
Let’s do it properly with a pre-release this time. Can you try 2.4.3-beta.1

Thanks

**Comment by windmueller** [comment]
Confirmed. With 2.4.3-beta.1, the integration loads and all sensors are available. 👍

**Comment by windmark** [comment]
I released 2.4.3

**Comment by windmueller** [comment]
Thank you for the excellent support and not just specifying the "minimal HA version" in the README. :)

Is there a donation link (SEPA, Wero, Paypal)?

**Comment by windmark** [comment]
Glad it worked, I’ll look into adding proper testing to prevent this next time https://github.com/MaxGrmm/EF-PowerOcean-TcpModbus/discussions/69

I personally don’t need any donation, but feel free to donate to climate charities :)

**Comment by windmueller** [comment]
> but feel free to donate to climate charities :)

As you wish. I just donated 10 € to [UNICEF](https://www.unicef.de/informieren/projekte/unicef-ziele-110800/klimaschutz-199412).
